FROM nvcr.io/nvidia/cuda:12.9.1-cudnn-runtime-ubuntu24.04
ENV DEBIAN_FRONTEND=noninteractive RECOGNIZER_ONNX_PROVIDER=cuda
WORKDIR /app
RUN apt update && apt install -y python3 python3-pip libasound2t64 && apt clean

COPY requirements.cuda.txt requirements.cuda.txt
RUN \
        pip3 install --break-system-packages sherpa-onnx=="1.12.40+cuda12.cudnn9" --no-index -f https://k2-fsa.github.io/sherpa/onnx/cuda.html && \
        pip3 install --break-system-packages -r requirements.cuda.txt
COPY . .
CMD ["python3", "quasistreaming-server.py"]