services:
  quasistreaming-gigam:
    build:
      context: .
      dockerfile: Dockerfile.cuda
    restart: unless-stopped
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
    environment:
      GIGAAM_MODEL_NAME: v3_e2e_rnnt
      GIGAAM_DEVICE: cuda
      GIGAAM_DOWNLOAD_ROOT: /app/.cache/gigaam
      VAD_MIN_SILENCE_DURATION: 1.25
      VAD_THRESHOLD: 0.48
      INPUT_GAIN: 1
      ASR_STREAMING_MODE: streaming
    volumes:
      - gigaam-v3-e2e-rnnt:/app/.cache/gigaam
    ports:
      - 127.0.0.1:8080:8080

volumes:
  gigaam-v3-e2e-rnnt:
