FROM python:3.12-slim
WORKDIR /app
ENV RECOGNIZER_ONNX_PROVIDER=cpu
RUN apt-get update && apt-get install -y --no-install-recommends libc++1 && rm -rf /var/lib/apt/lists/*
COPY requirements.cpu.txt requirements.cpu.txt
RUN pip install -r requirements.cpu.txt
COPY . .
CMD ["python", "quasistreaming-server.py"]
