FROM python:3.12-slim
WORKDIR /app
ENV RECOGNIZER_ONNX_PROVIDER=cpu
COPY requirements.cpu.txt requirements.cpu.txt
RUN pip install -r requirements.cpu.txt
COPY . .
CMD ["python", "quasistreaming-server.py"]